### ISSUE TITLE
Asks incorrectly to install package for locally-defined module

### ISSUE THREAD

**Issue by dpsanders** [mpastell/Weave.jl#101]
I get the error
```
WARNING: Something went wrong during weaving
ArgumentError("Module Models not found in current path.\nRun `Pkg.add(\"Models\")` to install the Models package.")
```
when  trying to weave a notebook in which I locally defined a module called `Models` (i.e. in a cell of the notebook).

**Comment by kleinschmidt** [comment]
I've had the same problem, with `include("MyModuleFile.jl")` which just defines `module MyModule end`

**Comment by kleinschmidt** [comment]
I think this has to do with the Weave.jl sandboxing (the whole doc is wrapped in a module that's generated on the fly), so any code you include or define locally isn't in `Main` but in that module.  In that case you can access your module by `using .MyModule`.

But I'm running into a slightly different problem. Let's say I have a type defined in my module, `MyModule.MyType`. I've saved some instances of that type to a JLD2 file from another session (Jupyter notebook or REPL).  When I go to load them, JLD2 somehow can't find the `MyModule.MyType`, even though I can construct new instances of that by calling `MyModule.MyType()`.  Perhaps this is a JLD2 bug but it's very frustrating when code that works perfectly well in Jupyter Notebook or the REPL breaks when run in a chunk.

**Comment by mpastell** [comment]
Yes, the bug is due to sandboxing. Sorry for not responding to this issue before. The only fix I can see is to run the code in `Main`, which will lose the advantage from using a separate Sandbox module for each document. 

I could add an option to run code in either Sandboxed or in Main. Would that be an acceptable solution? I think  I'd like to keep running in a Sandbox the default behavior unless there is strong preference to run things in `Main` by default.

**Comment by kleinschmidt** [comment]
Yeah I think that would work for my purposes.  I'm almost always running weave from a makefile (to ensure reproducibility).  But I agree it feels like a bandaid.  I wonder if it would be possible to intercept code that defines modules and eval it in Main instead.  Or if that would even help this situation...

**Comment by mpastell** [comment]
This should be fixed with the last commits with new `mod` argument which let's you specify where to run code. It defaults to `Main` as otherwise external packages don't work with 0.7-beta. Let me know if you still run into problems.
