### ISSUE TITLE
LaTeX/PDF outputs do not display all UTF-8 characters in code areas

### ISSUE THREAD

**Issue by noverby** [mpastell/Weave.jl#107]
The reason is that lstlisting does not support UTF-8 characters by default. 

**Potential solutions:**
1) lstlisting has the [literate](https://tex.stackexchange.com/questions/24528/having-problems-with-listings-and-utf-8-can-it-be-fixed) option which allows conversion of UTF-8 characters to LaTeX symbols. This requires specifying a conversion for every missing UTF-8 characters.
2) Use another LaTeX package for syntax highlighting such as [minted](https://github.com/gpoore/minted).

**Comment by mpastell** [comment]
This is related to using `Highlights.jl` and would probably be best to fix in that package. Can you give me an example about characters that don't work? Note that there is an option to use minted if you use LaTeX as a source format or you can output to markdown and use pandoc for the conversion to `.tex` and `.pdf`.

**Comment by noverby** [comment]
Example characters: 'p̂' and '₁'

**Comment by mpastell** [comment]
I chose to use minted instead of `Highlights.jl`so this should be fixed now.
