### ISSUE TITLE
don't override display

### ISSUE THREAD

**Issue by stevengj** [mpastell/Weave.jl#108]
It looks like you are overloading `display` in an attempt to customize output (although you are using the wrong method signature for that?).  This is the wrong way to do it — see the manual on [custom pretty printing](https://docs.julialang.org/en/release-0.6/manual/types/#Custom-pretty-printing-1).

To customize REPL output, you should override `Base.show(io::IO, x::MyType)` and/or `Base.show(io::IO, ::MIME"text/plain", x::MyType)`, as explained in the manual.

Overriding `display` directly will break IJulia, Juno, and other environments that have a custom `display` mechanism.

**Comment by mpastell** [comment]
Weave uses it's own custom display to capture output (text and figures) from the executed document. I do not really see a way to change this so that it would be compatible with IJulia, Juno etc.

**Comment by stevengj** [comment]
Oh, I see what you are doing now.  Using your custom `Report <: Display` type and defining `display(::Report, ...)` methods should be fine.  Doing this, and calling `pushdisplay(report)` to intercept `display` output, is the right thing to do, and should work fine with IJulia etcetera.

**Comment by stevengj** [comment]
Sorry for the false alarm; I did a search for packages that override `display`, and most of them were bugs, so I filed a bunch of issues at once, but I misunderstood this package.
