### ISSUE TITLE
Performance significantly decreased by using `ArgParse`

### ISSUE THREAD

**Issue by nathancarter** [mpastell/Weave.jl#110]
I'm working on [making an atom-build plugin](https://github.com/noseglid/atom-build/blob/master/create-provider.md) to support `Weave.jl`.  This would make it possible, when editing a `.jmd` file in [Atom](http://atom.github.io), to just press `Cmd+B` and have your document compiled.  This would be especially handy if the user opened the HTML results in a side-by-side pane, effectively mimicking the UX of a TeX app or RStudio, within Atom, for Julia.

The problem is that it takes about 35 seconds to run Weave.jl on even a trivial `.jmd` file on my one-year-old, high-end MacBook Pro.  I'm using this file:

    # This is an example Markdown file
    
    ```julia
    3*5
    ```
    
    This is some more text after the Julia code.

This significantly decreases the benefit of this use case.  For instance, in TeX and RStudio one is accustomed to striking the hotkey for recompiling and seeing their document compiled in just a few seconds.

I did some timing from the shell to narrow down the problem.  I got these results:

```sh
$ time ~/.julia/v0.6/Weave/bin/weave.jl example.jmd
INFO: Weaving chunk 1 from line 4
INFO: Report weaved to example.html

real	0m34.384s
user	0m33.445s
sys	0m0.801s
$ time julia -e 'using Weave'

real	0m5.516s
user	0m5.350s
sys	0m0.324s
$ time julia -e 'using ArgParse'

real	0m14.990s
user	0m14.604s
sys	0m0.428s
$ time julia -e '1+1'

real	0m0.529s
user	0m0.217s
sys	0m0.205s
```

To summarize:
 * Starting Julia is not the problem (0.5s).
 * Loading `Weave.jl` is only a small portion of the problem (5s).
 * Loading `ArgParse` is a huge part of the problem (15s).
 * Executing `Weave.jl` on my small file is the other half of the problem (the remaining 15s, I guess).

Therefore my question is whether there can be an improvement in performance here.  (I'm kind of surprised I'm even asking this question, given that one of Julia's main selling points is performance. 
 Maybe I'm doing something wrong?)  This boils down to two parts:
 1. The cost-benefit ratio for `ArgParse` is pretty high.  Could you get by with just a few loops coded manually?
 1. The `weave()` function  seems to take far too long to process such a small file.  What opportunities are there for performance improvements in there?  For example, is the `__precompile__(false)` at the top of `Weave.jl` necessary, and if not, would removing it help?

Alternately, if I'm doing something wrong, and could get better performance in some other way, I'd appreciate that help, too.  I'm new to Julia.

**Comment by davidanthoff** [comment]
We have that feature in the Julia VS Code extension and we would also benefit from any speed increase:)

**Comment by mpastell** [comment]
I agree that the slow startup is annoying, but I do not see a good way to fix it. I run weave from REPL and keep it open between the different runs in order to avoid the startup costs (also avoids loading ArgParse). My documents generally have plots in them and this also helps with the "time to first plot issue".

To answer your specific questions:

1. I'm happy to replace ArgParse with a better solution if you can make pull request or suggest a faster library for that purpose
2. Precompiling would help, but it needs to be disabled because Weave loads plotting libraries dynamically based on the document content. This issue maybe fixed with some future release of Julia.

**Comment by nathancarter** [comment]
Sorry, I'm new to Julia, so I don't have suggestions regarding alternatives to `ArgParse`.

Given that my file was a single arithmetic operation, the time-to-first-plot issue isn't at fault for the 15s to weave my file.  Do you know what part of the `weave()` function might be causing that slowness?

One solution I could implement in my atom build plugin would be to start a Julia instance the first time the user opens a `.jmd` file, and load all the necessary tools in the background, saving the overhead of loading `ArgParse` the first time, and so on.  But I worry, if it takes 15s just to call `weave()` on a seven-line file, that all that effort won't be worth it, because it will still be too slow.

Any further tips?

**Comment by mpastell** [comment]
The slowness is due to the function being JIT compiled the first time it's called. It will be much the faster the following times. I'm aware of the problem and if I new how to make it faster without removing features from the package I would have done it.

**Comment by nathancarter** [comment]
OK Good to know.  (Sorry, I'm still learning the details of Julia, so that might have been obvious to others, but wasn't to me.)  This means that if I start a Julia instance for the first compilation, and keep it in existence for future compilations, I can get a significant speedup.  That's very helpful.  Thanks!

**Comment by mpastell** [comment]
I managed to make this faster by adding a markdown to html conversion to Weave instead of using `Documenter` and loading JLD2 only when it's needed. This also allows to precompile Weave again so `using Weave` (after 1341aed) <1s. 

First weave still takes ~10s, I'll profile it to see if there is something obvious that I can fix.

**Comment by nathancarter** [comment]
Glad to hear of the progress, thanks for the work!

**Comment by mpastell** [comment]
Profiling didn't reveal any options to speed up the first weave without removing features so I'll close this issue.

**Comment by nathancarter** [comment]
Thank you very much for trying, and for the improvements you found!
