### ISSUE TITLE
How to specify the kernel version for Jupyter?

### ISSUE THREAD

**Issue by jlperla** [mpastell/Weave.jl#115]
I have JuliaPro 0.6.1.1 installed.  From the REPL, I creaed a simple `test.jmd` file, and called `convert_doc("test.jmd", "test.ipynb")`

The generated file has errors if if opened directly in Jupyter, but most importantly I think it is because of the following metadata in the generated file
```
  "nbformat_minor": 2,
  "metadata": {
    "language_info": {
      "file_extension": ".jl",
      "mimetype": "application/julia",
      "name": "julia",
      "version": "0.5.0"
    },
    "kernelspec": {
      "name": "julia-0.5",
      "display_name": "Julia 0.5.0",
      "language": "julia"
    }
  },
  "nbformat": 4
```
Any idea why it would default to Julia 0.5.0?  When I look at https://github.com/mpastell/Weave.jl/blob/master/src/writers.jl it seems to use the versions from the REPL it is running, and which I verified with a ` println("julia-$(VERSION.major).$(VERSION.minor)")` is the correct 0.6

**Comment by mpastell** [comment]
You can't specify it, this is a bug in current release which has been fixed in pending 0.5.0 tag.

**Comment by jlperla** [comment]
@mpastell Thanks.  When (and how) should I use the new version supporting the 0.6 kernel?  Is this something to wait for?

**Comment by mpastell** [comment]
You can checkout master (which can be broken at times, shouldn't be currently) or wait for https://github.com/JuliaLang/METADATA.jl/pull/12706 to be merged and run Pkg.update()
