### ISSUE TITLE
notebook export assumes global `jupyter` install

### ISSUE THREAD

**Issue by ssfrr** [mpastell/Weave.jl#122]
The code [here](https://github.com/mpastell/Weave.jl/blob/ce43dea594a1465755997235ab163aaca47fad52/src/Weave.jl#L167) assumes you have `jupyter` installed and in your PATH. If instead you have a `jupyter` installed by `IJulia.jl`, it lives at `IJulia.jupyter`

Seems like it should work to just run the executable at `$(IJulia.jupyter)-nbconvert`

**Comment by mpastell** [comment]
Yes, seems like a good idea. I'll change it.

**Comment by mpastell** [comment]
I didn't realize that `IJulia.jupyter` points to Jupyter location even if it's not installed by IJulia. So your version should work as long as IJulia is installed.
