### ISSUE TITLE
Error converting document to pdf

### ISSUE THREAD

**Issue by remoore** [mpastell/Weave.jl#123]
I have been using Weave to generate PDFs from Julia markdown, but this has stopped working.

If I run

```
using Weave
weave("gadfly_md_sample.jmd"; doctype="md2pdf", latex_cmd="pdflatex")
```

I get the following two warnings:

```
WARNING: _show is not defined for this backend. m=application/pdf
WARNING: Error converting document to pdf. Try running latex manually
```

I have tried running latex manually, but this doesn't work.

Any ideas why this isn't working for me?

Thanks in advance

Rob

**Comment by mpastell** [comment]
I think this issue is related to Gadfly. Can you save a pdf from Gadfly plot from the REPL?

**Comment by remoore** [comment]
Thanks for the response. I've just managed to get to the bottom of this.

I have a wrapper function for generating PDFs with Weave, which has keyword arguments with sensible defaults (for things like paths for caching figures and saving the PDFs). One of the arguments specifies the path to the tex template to use. I hadn't realised that this was using a local copy of "templates/julia_tex.tpl", which was outdated and causing the problem. It's using the copy stored in the package directory now.

Thanks for the help.

Rob
