### ISSUE TITLE
Pretty table formatting

### ISSUE THREAD

**Issue by akubisch** [mpastell/Weave.jl#125]
Hi!

First of all this is a really great and astonishingly fast package!
I am just wondering what would be the best practice for rendering tables? Let's say I have a simple `DataFrames::DataFrame` and want this to be prettily rendered using Weave.jl. Simply printing it does not work, so is there a better way?

Thanks a lot in advance!

**Comment by mpastell** [comment]
This depends a bit on output format, but you can call `display`. You should get html for `md2html` or latex output for `md2tex` or `md2pdf`. You can also specify the mimetype yourself:

```julia
x = DataFrame(x=randn(5))
display("text/html", x)
```  

I also sometimes write a custom display method if I want specify more exact formatting,

**Comment by akubisch** [comment]
Okay, this works pretty well for html output, but in case of `md2pdf` I get the mere julia output. Is this probably a bug or something I could easily fix?

**Comment by mpastell** [comment]
I do get latex output using Weave 0.5.1 and the latest DataFrames release. What do you get from REPL using?

```julia
display("text/latex", DataFrame(x=1:3))
```
I get

```
\begin{tabular}{r|c}
	& x\\
	\hline
	1 & 1 \\
	2 & 2 \\
	3 & 3 \\
\end{tabular}
```

**Comment by akubisch** [comment]
Okay, I'm having Weave 0.5.1 and just updated all packages. What I get is the following:
```julia
display("text/latex", DataFrame(x=1:3))
ERROR: MethodError: no method matching show(::Base.TTY, ::MIME{Symbol("text/latex")}, ::DataFrames.DataFrame)
Closest candidates are:
  show(::IO, ::MIME{Symbol("text/csv")}, ::DataFrames.AbstractDataFrame) at /home/alex/.julia/v0.6/DataFrames/src/abstractdataframe/io.jl:214
  show(::IO, ::MIME{Symbol("text/csv")}, ::Any) at datafmt.jl:707
  show(::IO, ::MIME{Symbol("text/tab-separated-values")}, ::DataFrames.AbstractDataFrame) at /home/alex/.julia/v0.6/DataFrames/src/abstractdataframe/io.jl:218
  ...
Stacktrace:
 [1] display(::TextDisplay, ::MIME{Symbol("text/latex")}, ::DataFrames.DataFrame) at ./multimedia.jl:158
 [2] display(::MIME{Symbol("text/latex")}, ::DataFrames.DataFrame) at ./multimedia.jl:232
 [3] display(::String, ::DataFrames.DataFrame) at ./multimedia.jl:126
```

**Comment by mpastell** [comment]
My guess would be that you have old versio  of DataFrames, it will not updated if you have depency requiring an old version.

**Comment by akubisch** [comment]
Great guess :-) When trying to checkout the latest master of DataFrames, I learned that Gadfly depended on the old version, since it does not work with Julia 0.6.2. Removing Gadfly and checking out DataFrames solved the issue. Thank you a lot!

**Comment by AhmedSalih3d** [comment]
> ```julia
> display("text/latex", DataFrame(x=1:3))
> ```

Any basic example of how to write my own show method? :)
