### ISSUE TITLE
Add references to figures in pandoc format

### ISSUE THREAD

**Issue by tpoisot** [mpastell/Weave.jl#127]
Filters like [pandoc-fignos](https://github.com/tomduck/pandoc-fignos) or [pandoc-crossef](https://github.com/lierdakil/pandoc-crossref) have a syntax to use figure ID in markdown.
If this package could add a doctype to export to this format, it would be great (it also makes citing figures much less of a hassle). 
I could also help with a PR if that's interesting.

**Comment by mpastell** [comment]
This is pending in #120, I think this can just be added to current pandoc output.

**Comment by tlnagy** [comment]
Some sort of figure numbering option would be fantastic to have. Does anyone know the advantages of pandoc-fignos vs crossref?

**Comment by tpoisot** [comment]
As far as I know the syntax is the same -- the difference is that pandoc-fignos is a relatively small Python module, the crossref filter is in Haskell and a bit more tricky to install.

**Comment by tpoisot** [comment]
So in practice, as long as we stick with the 99% of the syntax that's common, users can pick the filters they want/have at rendering time.

**Comment by mpastell** [comment]
I’ll try to look into this soon. Does #120 implement what you need?

**Comment by tpoisot** [comment]
Absolutely!

**Comment by tpoisot** [comment]
I tried to use `--filter pandoc-fignos` and this is not working -- my guess is that it's because these are passed as options (before the output). It doesn't work with the standard `--filter pandoc-citeproc` either.
