### ISSUE TITLE
Add table of contents option for output?

### ISSUE THREAD

**Issue by kescobo** [mpastell/Weave.jl#132]
For very long documents, automatic generation of a TOC based on headers would be super useful. Pandoc already [has options](https://pandoc.org/MANUAL.html) for this:

>--toc, --table-of-contents
>Include an automatically generated table of contents (or, in the case of latex, context, docx, odt, opendocument, rst, or ms, an instruction to create one) in the output document. This option has no effect on man, docbook4, docbook5, or jats output.
>
>--toc-depth=NUMBER
>Specify the number of section levels to include in the table of contents. The default is 3 (which means that level 1, 2, and 3 headers will be listed in the contents).

So it seems like it should be relatively straightforward to add for pandoc builds. Not sure about the others (I personally need it most for markdown to html and markdown to ipynb. I could take a stab at this, but I'm not super familar with this codebase so any direction would be helpful

**Comment by mpastell** [comment]
I added a `pandoc_options` keyword to pass options directly to pandoc so now you can get table of contents if you like using:

```
weave("somefile.jmd", doctype="pandoc2html", pandoc_options=["--toc"])
```

It would not be very difficult to get a table of contents using Julia Markdown, but it could be better to implement pandoc-like features in some other package than Weave.
