### ISSUE TITLE
Julia 1.0 update

### ISSUE THREAD

**Issue by mpastell** [mpastell/Weave.jl#136]
The development target for current master is Julia 1.0, and the package works using 0.7. Remaining deprecation warnings (errors on 1.0) come from dependencies (`YAML.jl`, `Mustache.jl` and `Highlights.jl` .

You can also use the development version of `YAML.jl` to get rid of most deprecation warnings.

TODO:
- [x] Update plotting Plots.jl support. Works with combination of Plots and GR master.
- [x]  Update Gadfly support
- [x]  Update caching when JLD2 is updated
- [x]  Fix remaining deprecation warnings
- [x]  Fix remaining deprecation warnings from test and example documents
- [x] Add Project.toml
- [x] Move to using Requires.jl for optional plot displays

**Comment by mpastell** [comment]
Weave now runs on 1.0, release v0.6.1 has been tagged https://github.com/JuliaLang/METADATA.jl/pull/16974 . I'll leave the issue open for fixing caching and possibly Gadfly support.

**Comment by tlnagy** [comment]
Gadfly master now works on Julia 1.0. See https://github.com/GiovineItalia/Gadfly.jl/issues/1192. We expect to tag a new release this weekend.

**Comment by cortner** [comment]
just tried Weave.jl on j 1.0, but it generates pre v0.6 syntax.
```
julia> d = {"Weave" => "testing"}
Error: syntax: { } vector syntax is discontinued
```
The version is 
```
  [44d3d7a6] Weave v0.6.2
```

**Comment by mpastell** [comment]
Gadfly support has been added
