### ISSUE TITLE
delete tmp directorys when output type is md2pdf

### ISSUE THREAD

**Issue by YSanchezAraujo** [mpastell/Weave.jl#140]
using `md2html `a tmp directory is created  in `out_path`while the html file is being generated and once it's done that directory is deleted by weave, when using `md2pdf` the behavior is that these directories remain after successful creation of the pdf file. Is this the expected behavior?

**Comment by mpastell** [comment]
That was a bug that should be fixed with the last commit. Thanks for reporting.
