### ISSUE TITLE
Weave and Turing.jl

### ISSUE THREAD

**Issue by cpfiffer** [mpastell/Weave.jl#145]
Hey folks. Over at [Turing.jl](https://github.com/TuringLang/Turing.jl) we've been trying to find a good solution to making working tutorials, but I have run into some issues running our code through Weave. Our internal issue is [here](https://github.com/TuringLang/Turing.jl/issues/517).

Here's the output when weaving to pretty much any format (Julia 1.0):

````julia
using Turing
using MCMCChain, Plots, Distributions

# Define a simple Normal model with unknown mean and variance.
@model gdemo(x) = begin
  s ~ InverseGamma(2,3)
  m ~ Normal(0,sqrt(s))
  x[1] ~ Normal(m, sqrt(s))
  x[2] ~ Normal(m, sqrt(s))
  return s, m
end

#  Run sampler, collect results
c1 = sample(gdemo([1.5, 2]), SMC(1000))
````

<pre class="julia-error">
ERROR: LoadError: UndefVarError: @~ not defined
in expression starting at &lt;macrocall&gt;:-1
</pre>

````julia

# Summarise results (currently requires the master branch from MCMCChain)
describe(c1)
````

<pre class="julia-error">
ERROR: UndefVarError: c1 not defined
</pre>

````julia

# Plot and save results
p = plot(c1)
````

<pre class="julia-error">
ERROR: UndefVarError: c1 not defined
</pre>

Do you folks have any idea why this might be happening? It's the same way when we run cells through Literate + Documenter, so it may be possible that it's on our end.

**Comment by mpastell** [comment]
Weave runs code in a sandbox module by default, but it seems you need to run this code in `Main`. You can do it using:

```julia
weave("model.jl", mod=Main)
```

**Comment by cpfiffer** [comment]
Works for me, thank you!
