### ISSUE TITLE
Markdown output from blocks

### ISSUE THREAD

**Issue by ChrisRackauckas** [mpastell/Weave.jl#156]
In the last block of this:

https://htmlpreview.github.io/?https://github.com/JuliaDiffEq/DiffEqBenchmarks.jl/blob/9f2c1a96db339251e00eaf825ae60c9195070a66/html/NonStiffODE/linear_wpd.html

I just want procedurally-generated appendices. This works, but currently by outputting this string the result looks different from the rest of the outputs. I was hoping to see if I could instead return Markdown and have it be correctly styled.

**Comment by tlnagy** [comment]
AFAIK, @mpastell has been quiet for a while now so maybe a potential solution until he comes back (or someone forks this repo) is to edit the HTML post-write and change the CSS class.

**Comment by mpastell** [comment]
Display of markdown objects should work again with the current release.

**Comment by mpastell** [comment]
I reopened as I just realized that Weave doens't convert the markdown output to html or latex. So this should currently work with pandoc, but it doesn't quite work with `md2html`.  

You actually get best appearance (or at least best control) by outputting an object that can be displayed in both html and latex in which case Weave will choose the best option for the output document,

**Comment by mpastell** [comment]
You can now output markdown and it will be rendered in html and latex. e.g.

```julia
display("text/markdown",
"""

# Small markdown sample

**Hello** from `code` block.

""")
```
