### ISSUE TITLE
Capturing custom types

### ISSUE THREAD

**Issue by greimel** [mpastell/Weave.jl#168]
This doesn't work: 

`test.jl`:

```
#' Problem

struct A
  x
end

# A(5);
A(5)
```

`using Weave; weave("test.jl", doctype="md2html")` hangs forever at "Weaving chunk 1 from line 2" .

Adding a `;` to the last line makes it work.

**Comment by mpastell** [comment]
Good, it seems that #165 has fixed a lot of things... I'll publish a new release shortly.
