### ISSUE TITLE
FR: New css class for output

### ISSUE THREAD

**Issue by tobydriscoll** [mpastell/Weave.jl#171]
Currently the class of an interactive output element is "hljl", which is the same as code. To my eye output is not easily enough distinguished from code as a result. I'd like md2html to use a separate class such as "output" that could be styled differently via css.

**Comment by mpastell** [comment]
Seems like a useful request. Can you make a pull request for this?

**Comment by tobydriscoll** [comment]
I've taken a crack at it with https://github.com/mpastell/Weave.jl/pull/172.

**Comment by mpastell** [comment]
Closed with #172
