### ISSUE TITLE
Unicode indexing error?

### ISSUE THREAD

**Issue by ChrisRackauckas** [mpastell/Weave.jl#175]
Here's an example notebook which fails:

---------------------------------------------------------

---
title: Unit Checked Arithmetic via Unitful.jl
author: Chris Rackauckas
---

Units and dimensional analysis are standard tools across the sciences for checking the correctness of your equation. However, most ODE solvers only allow for the equation to be in dimensionless form, leaving it up to the user to both convert the equation to a dimensionless form, punch in the equations, and hopefully not make an error along the way.

DifferentialEquations.jl allows for one to use Unitful.jl to have unit-checked arithmetic natively in the solvers. Given the dispatch implementation of the Unitful, this has little overhead.

## Using Unitful

To use Unitful, you need to have the package installed. Then you can add units to your variables. For example:

```julia
using Unitful
t = 1.0u"s"
```

Notice that `t` is a variable with units in seconds. If we make another value with seconds, they can add

```julia
t2 = 1.02u"s"
t+t2
```

and they can multiply:

```julia
t*t2
```

You can even do rational roots:

```julia
sqrt(t)
```

Many operations work. These operations will check to make sure units are correct, and will throw an error for incorrect operations:

```julia
t + sqrt(t)
```

## Using Unitful with DifferentialEquations.jl

Just like with other number systems, you can choose the units for your numbers by simply specifying the units of the initial condition and the timestep. For example, to solve the linear ODE where the variable has units of Newton's and `t` is in Seconds, we would use:

```julia
using DifferentialEquations
f = (y,p,t) -> 0.5*y
u0 = 1.5u"N"
prob = ODEProblem(f,u0,(0.0u"s",1.0u"s"))
sol = solve(prob,Tsit5())
```

Notice that we recieved a unit mismatch error. This is correctly so! Remember that for an ODE:

```math
\frac{dy}{dt} = f(t,y)
```

we must have that `f` is a rate, i.e. `f` is a change in `y` per unit time. So we need to fix the units of `f` in our example to be `N/s`. Notice that we then do not receive an error if we do the following:

```julia
f = (y,p,t) -> 0.5*y/3.0u"s"
prob = ODEProblem(f,u0,(0.0u"s",1.0u"s"))
sol = solve(prob,Tsit5())
```

This gives a a normal solution object. Notice that the values are all with the correct units:

```julia
print(sol[:])
```

We can plot the solution using the plot recipe.

```julia
#Pkg.clone("https://github.com/ajkeller34/UnitfulPlots.jl")
using UnitfulPlots, Plots
gr()
plot(sol.t,sol[:],lw=3)
```

Notice that here we pulled the units for the label directly from the solution. Thus if the units change, the labels will change automatically.

---------------------------------------------------------

The error is:

```
StringIndexError("Unitful.Quantity{Float64,�*�*�^-2,Unitful.FreeUnits{(N,),�*�*�^-2,nothing}}[1.5 N, 1.53621 N, 1.77204 N]", 75)
string_index_err(::String, ::Int64) at string.jl:12
Type at substring.jl:32 [inlined]
Type at substring.jl:38 [inlined]
Type at substring.jl:44 [inlined]
Type at substring.jl:40 [inlined]
getindex(::SubString{String}, ::UnitRange{Int64}) at substring.jl:204
wrapline(::SubString{String}, ::Int64) at format.jl:322
wraplines(::String, ::Int64) at format.jl:310
format_chunk(::Weave.CodeChunk, ::Dict{Symbol,Any}, ::Weave.JMarkdown2HTML) at format.jl:186
format(::Weave.WeaveDoc) at format.jl:33
#weave#16(::String, ::Symbol, ::String, ::Dict{Symbol,String}, ::Symbol, ::String, ::Nothing, ::String, ::Symbol, ::Bool, ::Nothing, ::Nothing, ::Nothing, ::Array{String,1}, ::String, ::typeof(Weave.weave), ::String) at Weave.jl:113
#weave at none:0 [inlined]
weave_file(::String, ::String, ::Tuple{Symbol,Symbol,Symbol}) at DiffEqTutorials.jl:21
weave_file(::String, ::String) at DiffEqTutorials.jl:8
top-level scope at none:0
```

It looks like an error with indexing unicode incorrectly, but is hard to isolate.

**Comment by mpastell** [comment]
Thanks for reporting! There seems to be a bug in wrapping the output https://github.com/mpastell/Weave.jl/blob/1e630ed825e8c4c696e5d3fd4fe571a19b892511/src/format.jl#L319, you can avoid it by using `wrap=false`.

**Comment by ChrisRackauckas** [comment]
I'm getting unsupported kwarg for `wrap`.

**Comment by ChrisRackauckas** [comment]
`weave(tmp,doctype = "md2html",out_path=dir,args=args, wrap=false)`

**Comment by mpastell** [comment]
You need to use it as a chunk option ` ```julia; wrap=false ` . See: http://weavejl.mpastell.com/stable/chunk_options/

**Comment by ChrisRackauckas** [comment]
Can there be a global way of disabling the wrap? I don't want the wrapping anyways. It makes the html outputs look weird. Example: https://htmlpreview.github.io/?https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/html/number_types.html

**Comment by ChrisRackauckas** [comment]
`wrap=false` fixes the html output, but the PDF output still is having issues.

**Comment by mpastell** [comment]
You can use `set_chunk_defaults` function to set global defaults, it would make sense to allow passing default options directly to `weave` if you'd have time to add the feature.

**Comment by mpastell** [comment]
OK, this should now be fixed.

**Comment by mpastell** [comment]
You can now set default options in document header: http://weavejl.mpastell.com/dev/chunk_options/#Set-default-chunk-options-1
