### ISSUE TITLE
HTML rendering does not render math

### ISSUE THREAD

**Issue by ChrisRackauckas** [mpastell/Weave.jl#178]
Example: https://htmlpreview.github.io/?https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/html/ode_introduction.html

**Comment by mpastell** [comment]
Math renders fine for me locally (when I download the document from your repo), could this be an issue with htmlpreview?

**Comment by mpastell** [comment]
You can use `set_chunk_defaults` function to set global defaults, it would make sense to allow passing default options directly to `weave` if you'd have time to add the feature.

**Comment by ChrisRackauckas** [comment]
Yes, thanks. Fixed by rendering via Github Pages
