### ISSUE TITLE
Notebook output heading style

### ISSUE THREAD

**Issue by ChrisRackauckas** [mpastell/Weave.jl#179]
Here's a notebook generated by Weave: https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/notebook/number_types.ipynb . It looks like it should have a `#` heading for the title and a `##` for the author, but right now the title is not a heading at all and the author has a large heading.

**Comment by mpastell** [comment]
Weave doesn't currently do any formatting to the title block in notebook output (I don't why it renders like that), but clearly it should. I'll try to fix this soon.
