### ISSUE TITLE
Removing a block when converting to a notebook or adding a block when not making a notebook

### ISSUE THREAD

**Issue by ChrisRackauckas** [mpastell/Weave.jl#183]
In the examples from DiffEqTutorials.jl like https://github.com/JuliaDiffEq/DiffEqTutorials.jl/blob/master/notebook/introduction/ode_introduction.ipynb , we would like to have an appendix which gives information about the runstate of the computer, like in http://juliadiffeq.org/DiffEqTutorials.jl/html/introduction/ode_introduction.html , but not in the notebook. I haven't found a way to easily programmatically add/delete blocks dependent on the output format.

**Comment by mpastell** [comment]
This isn't possible at the moment, but seems also generally useful. I can add it.

**Comment by mpastell** [comment]
I added an option for this with 056db51 . You can now use: ` ```julia; skip="notebook" ` chunk option to omit a chunk from notebook.

I'll add documentation and support for skipping chunks from other formats at some point.

**Comment by ChrisRackauckas** [comment]
Is there way to do this and output the correctly formatted header?

```
---
title: Test
author: Chris Rackauckas
---

This is a test of the builder system.

```julia{echo=false,skip="notebook"}
using Markdown
using DiffEqTutorials
show(stdout, "text/markdown", Markdown.parse("## Appendix"))
DiffEqTutorials.tutorial_footer(WEAVE_ARGS[:folder],WEAVE_ARGS[:file])
```
```

gives me

<img width="797" alt="capture" src="https://user-images.githubusercontent.com/1814174/53524054-726c5900-3aac-11e9-88d5-e22739bda0c5.PNG">

**Comment by mpastell** [comment]
Just to get the header right you can use

```julia
display("text/markdown", "## Appendix")
```
I also tried to implement a markdown formatted footer, the only issue there is that Weave can't tell in which order output appears in display and stdout -> You can't mix display and print commands. IJulia has the same problem so I don't think there is an easy fix. 

Anyway, here is a version that almost works (meaning that the output from Pkg is not exactly right, unfortunately Pkg.status only outputs to stdout).

```julia
    ```julia; hold=true
    using InteractiveUtils
    using Pkg
    function tutorial_footer(folder=nothing, file=nothing)
        display("text/markdown", """
        ## Appendix

         These benchmarks are part of the DiffEqTutorials.jl repository, found at: <https://github.com/JuliaDiffEq/DiffEqTutorials.jl>
        """)
        if folder !== nothing && file !== nothing
            display("text/markdown", """
            To locally run this tutorial, do the following commands:
            ```
            using DiffEqTutorials
            DiffEqTutorials.weave_file("$folder","$file")
            ```
            """)
        end
        display("text/markdown", "Computer Information:")
        vinfo = sprint(InteractiveUtils.versioninfo)
        display("text/markdown",  """
        ```
        $(vinfo)
        ```
        """)

        ctx = Pkg.API.Context()
        pkgs = Pkg.Display.status(Pkg.API.Context(), use_as_api=true);

        display("text/markdown", """
        Package Information:
        """)

        md = ""
        md *= "```\nStatus `$(ctx.env.project_file)`\n"

        for pkg in pkgs
            md *= "[$(pkg.uuid)] $(pkg.name) $(pkg.old.ver)\n"
        end
        md *= "```"
        display("text/markdown", md)
    end

    tutorial_footer("", "")
    ```
```

**Comment by mpastell** [comment]
Here is the output:

![image](https://user-images.githubusercontent.com/430863/53552533-2c62d400-3b44-11e9-84d2-e8c8d9ed94e9.png)

**Comment by ChrisRackauckas** [comment]
Looks great!
