### ISSUE TITLE
Notebook generation errors on Windows, but is successful

### ISSUE THREAD

**Issue by ChrisRackauckas** [mpastell/Weave.jl#187]
Generating the notebooks I get

```
[ Info: Running nbconvert
Error executing Jupyter command 'nbconvert': [Errno 'jupyter-nbconvert' not found] 2
ERROR: failed process: Process(`'C:\Users\accou\.julia\conda\3\Scripts\jupyter.exe' nbconvert --ExecutePreprocessor.timeout=-1 --to notebook --execute 'C:\Users\accou\.julia\external\DiffEqTutorials.jl\src\..\notebook\introduction/ode_introduction.ipynb' --output 'C:\Users\accou\.julia\external\DiffEqTutorials.jl\src\..\notebook\introduction/ode_introduction.ipynb'`, ProcessExited(1)) [1]
```

However, it outputs the notebooks just fine so it's not a big deal. I wonder if this is just a Windows issue?

**Comment by mpastell** [comment]
Seems strange, I don’t get the same error on Windows so I can’t really debug.

**Comment by mpastell** [comment]
Have you checked that the notebooks are executed? The error seems to indicate that Jupyter is not installed.

**Comment by ChrisRackauckas** [comment]
The notebooks are not executed. Are they supposed to be? Jupyter is installed via Conda.jl and not available directly in the command line.

**Comment by mpastell** [comment]
Yes, they should be if you call `notebook`, otherwise you can just call `convert_doc`. IJulia installs `nbconvert` for me so I'm not sure why it seems to be missing on your setup.

**Comment by ChrisRackauckas** [comment]
Okay, I just switched to `convert_doc`, and this issue seems to be a user issue of not having `jupyter` available in the command line.
