### ISSUE TITLE
plotlyjs gives Warning: ERROR: UndefVarError occurred, including output in Weaved document

### ISSUE THREAD

**Issue by isaacsas** [mpastell/Weave.jl#188]
A simple file with:

~~~
# Testing plotlyjs

```julia
using Plots
plotlyjs()
plot(1:100,1:100,fmt=:svg)
```
~~~

gives 
```
julia> weave("plotlyjstest.jmd", doctype="md2html")
[ Info: Weaving chunk 1 from line 3
┌ Warning: ERROR: UndefVarError occurred, including output in Weaved document
└ @ Weave ~/.julia/dev/Weave/src/run.jl:243
[ Info: Report weaved to plotlyjstest.html
```
and generates no figure. No such problems using `pyplot()` or `gr()`.

I'm using the latest master for Weave.jl.

**Comment by isaacsas** [comment]
In the generated html file the output is:
```
ERROR: UndefVarError: data not defined
```

**Comment by mpastell** [comment]
The last I tested SVG output for plotlyjs was broken also outside of Weave. Does this code work outside of Weave i.e can you save an svg?

**Comment by isaacsas** [comment]
On my machine (Mac with the latest Plots and Plotlyjs releases), both Jupyter notebooks and the REPL correctly display `fmt=:svg` plots using the Plotlyjs backend. But you are right, `savefig` crashes out with an IO error.

**Comment by isaacsas** [comment]
Since the `savefig` issue is on one of the Plots.jl or PlotlyJs.jl sides I'll close this. Thanks for the quick response!
