### ISSUE TITLE
Math in Jupyter

### ISSUE THREAD

**Issue by arnavs** [mpastell/Weave.jl#193]
@jlperla and I have been some issues with math in `Weave.notebook()`. 

In particular, syntax like the following works fine weaved to HTML, but not to notebook (ignore the `\` characters, as I couldn't get GH to render it without them). 

I tried `convert_doc()` instead of `notebook()`, but it didn't make much difference. 

```
\```math 
\begin{equation} 
...some thing 
\end{equation}
\```
```

**Comment by mpastell** [comment]
See here for a solution: https://github.com/mpastell/Weave.jl/issues/182#issuecomment-467929113 . More generally Weave doesn’t do any formatting on the markdown passed to Jupyter so you need use subset of markdown that is compatible with both.

**Comment by arnavs** [comment]
Right, the issue is that we have one set of source Markdown which we are weaving jointly to HTML and Jupyter, and the `$$` syntax breaks the HTML. 

Is there a solution which is compatible with both outputs?

**Comment by mpastell** [comment]
$$ should work with both formats with the latest release, can you check that you have updated Weave.

**Comment by arnavs** [comment]
Yeah, I'm on `v0.8.1`. Let me find a minimal example.

**Comment by arnavs** [comment]
Nevermind, I confused the fence and `$$` syntax. Will switch over to `$$` then for the math blocks.

**Comment by arnavs** [comment]
Wait, sorry, I remember the issue. If we switch to the `$$` syntax, that works for math blocks, but how do we do inline math without the double backticks?

**Comment by arnavs** [comment]
Closing as I think the solution is  just to use `$`.
