### ISSUE TITLE
How to weave a Jupyter notebook to pdf?

### ISSUE THREAD

**Issue by sbacelar** [mpastell/Weave.jl#201]
I tried to use the documentation example `weave("notebook.ipynb")` but the result was `notebook.md`.

**Comment by tlnagy** [comment]
On Weave master, try to run `Weave.notebook("notebook.ipynb")`, this should be fixed by #196

**Comment by mpastell** [comment]
`weave("notebook.ipynb", docformat = "md2pdf")` should work.
