### ISSUE TITLE
Plots different in pdf and HTML

### ISSUE THREAD

**Issue by Wikunia** [mpastell/Weave.jl#210]
I wanted to create a pdf with 12 subplots each containing around 500,000 dots which seemed to be too much for pdf and I didn't really understood why. I thought it's rendered as an image once and then put into the pdf but seems like there is more going on. BTW the result was that I wasn't able to load the pdf with my evince viewer. It was 2.2MB in size but kept loading...
Anyway I reduced the number of points to about 1,000 - 50,000 each and I was able to load the pdf but there where no dots in most of the plots. I tried to convert it to HTML instead and it worked like a charm. The pdf displayed only the ones which have less than 2,000 dots which you can see below. Additionally I expected the color to be standard blue as well instead of black. 

Output in HTML:
![weave_html](https://user-images.githubusercontent.com/4931746/58320633-67f7fc00-7e1c-11e9-9f57-abca7ba05bce.png)

Output in PDF:
![weave_pdf](https://user-images.githubusercontent.com/4931746/58320635-67f7fc00-7e1c-11e9-95a1-fa6c1ecd393d.png)

**Comment by tlnagy** [comment]
Are you sure that this is a Weave specific behavior? What happens if you try to save the plots as html (probably svg?) or as a pdf separately from Weave?

**Comment by Wikunia** [comment]
Thanks for your reply @tlnagy when I save it as pdf using Plots I run into the same problem.
