### ISSUE TITLE
math block is not correctly converted from jmd to ipynb

### ISSUE THREAD

**Issue by Roger-luo** [mpastell/Weave.jl#211]
The math block in jmd should be converted to

    $$
    $$

but it remains to be

    ```math
    ```

when using `convert_doc` to convert `jmd` to notebooks

**Comment by arnavs** [comment]
The ideal function for this is `Weave.notebook("some_file.jmd")`. Give that a shot and see if it works. Note that, unless you have Jupyter and `nbconvert` installed in your Julian (i.e., `Conda.jl`) Python, you'll need to use `https://github.com/arnavs/Weave.jl`, which uses whatever you've linked to `Jupiter nbconvert`.

**Comment by tlnagy** [comment]
@arnavs' solution should now work on Weave master with #196 and will soon make it into stable.

**Comment by mpastell** [comment]
The solution here is to use `$$` also in `.jmd`. Weave doesn't convert the markdown blocks so it's up to you to use Markdown that is compatible with Jupyter and Weave. The only difference between `convert_doc` is and `notebook` is that the latter runs nbconvert to run code in addition to converting.
