### ISSUE TITLE
notebook() arguments aren't kwargs

### ISSUE THREAD

**Issue by arnavs** [mpastell/Weave.jl#212]
https://github.com/mpastell/Weave.jl/blob/c9a814759dba764931582f7dc91e0d92633a7e4d/src/Weave.jl#L173-L184

For example, if you want to set a `nbconvert_options` string, you also need to set an `out_path` and a `timeout`, even if you don't intend to fiddle with those defaults.

**Comment by tlnagy** [comment]
Is this fixed by #196?

**Comment by arnavs** [comment]
Sorry, you're right, I did fix it with the reorganization in the PR. Closing now.
