### ISSUE TITLE
Usage as a Lexicon backend?

### ISSUE THREAD

**Issue by MichaelHatherly** [mpastell/Weave.jl#26]
Hi @mpastell, I've been looking around recently for a better rendering backend to replace Lexicon's current offering. Weave looks like it might be exactly what I'm looking for! I've not had a chance to dig into the package yet, but was wandering what your opinion would be on this since I see you're using Docile/Lexicon for some docs already?

**Comment by mpastell** [comment]
That would definetly be interesting. I was actually planning to write the next version of docs using Weave and Docile.Interface anyway.

**Comment by mpastell** [comment]
I'm making some changes on how parsing and running the code works in `chunk_types` branch so you might not want to look at the code before that is finished.

**Comment by MichaelHatherly** [comment]
Thanks for the input. Note that there have been some changes on Docile master recently, though Docile.Interface hasn't changed significantly.

**Comment by mpastell** [comment]
What features do you expect from a backend? Let me know if I can help. Do you plan to develop Lexicon into something that will replace Sphinx?

**Comment by MichaelHatherly** [comment]
I've mostly been looking for generating output from code block, which Weave provides. Multiple output formats as well is great to have.

Feature parity with Sphinx as a long term goal would be great, though I've not given that a huge amount of thought yet and I'm sure would be a much bigger job than I currently have the time for. I harm dreaming big though :)
