### ISSUE TITLE
Support for Plots.jl?

### ISSUE THREAD

**Issue by joshday** [mpastell/Weave.jl#36]
This would indirectly add support for backends that Plots.jl supports (http://plots.readthedocs.org/en/latest/backends/).

**Comment by mpastell** [comment]
Thanks for the suggestion. I've started working on this now in the https://github.com/mpastell/Weave.jl/tree/plotsjl branch. Plots.jl now works more or less if you want to try it. Just use `plotlib = nothing` when you call weave.

I decided to implement generic support for svg, png, html etc. and the output is probably broken for some cases. I will merge back to master once its done.

**Comment by joshday** [comment]
Sounds great!  Thanks for the quick response.

**Comment by mpastell** [comment]
This is now merged in master and it should work, but the testing is limited. Let me know how it works for you if you have time to test it.
