### ISSUE TITLE
More informative error message when weaving

### ISSUE THREAD

**Issue by gragusa** [mpastell/Weave.jl#38]
I have a `markdown` document (`MCMC.md`). When I try to weave it from within `Julia` I get:

```
weave("MCMC.md", doctype="md2html", out_path="html", plotlib="Gadfly", informat="markdown")
INFO: Weaving chunk 1 from line 66
INFO: Weaving chunk 2 from line 72
INFO: Weaving chunk 3 from line 79
INFO: Weaving chunk 4 from line 83
INFO: Weaving chunk 5 from line 92
INFO: Weaving chunk 6 from line 108
INFO: Weaving chunk 7 from line 120
INFO: Weaving chunk 8 from line 172
INFO: Weaving chunk 9 from line 208
INFO: Weaving chunk 10 from line 214
INFO: Weaving chunk 11 from line 218
INFO: Weaving chunk 12 from line 227
INFO: Weaving chunk 13 from line 271
INFO: Weaving chunk 14 from line 287
INFO: Weaving chunk 15 from line 301
INFO: Weaving chunk 16 from line 306
ERROR: Unable to convert to html, check that you have pandoc installed and in your path
 in pandoc2html at /Users/neox/.julia/v0.4/Weave/src/pandoc.jl:32
 in weave at /Users/neox/.julia/v0.4/Weave/src/Weave.jl:120
```

However, if I call `pandoc` from the shell

```
pandoc -R -s --mathjax="" --self-contained --highlight-style=tango --template ~/.julia/v0.4/Weave/templates/pandoc_skeleton.html --include-in-header=/Users/neox/.julia/v0.4/Weave/templates/pandoc_skeleton.css -o mcmc.html MCMC.md
```

the html file is produces without error. It is not a path problem, because weaving works on other documents. 

So I guess it would be useful to have the actual message returned by the system call to pandoc.

**Comment by mpastell** [comment]
I agree, I will need do fix it.

Are you using Weave 0.12? There is a bug with pandoc and setting `out_path` in 0.11 that could be the cause of the error you're getting.

**Comment by gragusa** [comment]
I am using master. And it works on other files without problem on the same
session. I will look into it once I am in front of a real keyboard.

**Comment by mpastell** [comment]
I did a quick fix on error messages, its in master now  d5f1fd4 . 

Would be good to know why its failing! An option would be to use a file as input to pandoc instead of a pipe if that is somehow causing the problem.

**Comment by gragusa** [comment]
Now I get a more informative message....Unfortunately not much more informative...:

```
WARNING: Error converting document to HTML
ERROR: MethodError: `data` has no method matching data(::Date)
 in pandoc2html at /Users/neox/.julia/v0.4/Weave/src/pandoc.jl:35
 in weave at /Users/neox/.julia/v0.4/Weave/src/Weave.jl:88
```

I looked into the code and the only place where `pandoc2html` is messing with `Date` is the call to `now()`. This would explain why I can convert to `md2pdf` without problem.

**Comment by mpastell** [comment]
Can you try what happens if you set the `wtime` to a string manually or if you change

```
wtime =  Date(now())
```
to

```
wtime =  string(Date(now()))
```

Also could you share the document thats causing the error confidentially?
