### ISSUE TITLE
Add chunk option `prompt`

### ISSUE THREAD

**Issue by gragusa** [mpastell/Weave.jl#39]
Would it make sense to add a  `prompt` chunk option as in Knitr. `prompt=false`would not output `julia>`?

**Comment by mpastell** [comment]
Thanks for the suggestion, I will add it.

**Comment by gragusa** [comment]
I was thinking to add it myself (I am very interested in the project and I
plan to start contributing), but I think there is something more profound
to think about.

`Weave` treats chunk output differently depending on whether `term` is
`true` or `false`. In the former case, the output is put in the same chunk
as the input. In the latter case, the only output shown is a plot or a
message of the command (for instance the result of a `prinln` call).

Would it make more sense to have  always the output in a different output
chunk? If one then want to hide the results he would use `results=hidden`.

**Comment by mpastell** [comment]
You are of course very welcome to contribute and make pull requests. 

As for the issue of showing output: the `term=true` is mean to emulate terminal and I would like to keep it as it is. It is meant for showing Julia code in tutorial style.

The main difference in terms of implementation between `true`  and `term=false`(I call these script chunks) is that it `display` is called for each expression/variable. This is what I usually use and think this is the sensible thing. Calling display seems uncalled for if you don't want to display everything by default and makes the code slower especially for plots and objects outputting a lot of html.

 I'm quite happy with the way the current master works, output is now triggered for:

- Writing to stdin
- Calling display
- Gadfly plots
- Variables on their own
- If the last line is a function call that returns output e.g. `plot(1:10)`


I haven't tested it that much and If there is something that people think should be changed I'm open to suggestions.

What about the option to to add `display=true` that would always call display for each expression, that would behave like the term chunk, but having code and output in separate chunks and would also display "rich" output like "text/html"?

**Comment by gragusa** [comment]
Yes. `display=true` is what I was looking for....

**Comment by mpastell** [comment]
If you'd like to add it I think all you need to do is to modify the capture_output method and add a default chunk option, which I'd like to ne false.

________________________________
Lähettäjä: Giuseppe Ragusa<mailto:notifications@github.com>
Lähetetty: ‎29.‎4.‎2016 19:34
Vastaanottaja: mpastell/Weave.jl<mailto:Weave.jl@noreply.github.com>
Kopio: Pastell, Matti E<mailto:matti.pastell@helsinki.fi>; Comment<mailto:comment@noreply.github.com>
Aihe: Re: [mpastell/Weave.jl] Add chunk option `prompt` (#39)


Yes. display=true is what I was looking for....

**Comment by gragusa** [comment]
Will give it a shot soon
