### ISSUE TITLE
Raleway

### ISSUE THREAD

**Issue by gragusa** [mpastell/Weave.jl#45]
Exporting to `md2html` uses the Raleway font from google font foundry. I am getting many instances in which the conversion fails because `pandoc` is not able to fetch the font.

 Would it be better to have the basic skeleton not to depend on any external resource (except of course for mathjax)?

**Comment by mpastell** [comment]
Would this be fixed by not using `--self-contained`?

**Comment by gragusa** [comment]
Yes, but it is not clear that you want to do that. I think the result of a  call to `weave` with `output=md2html` should be as vanilla as possible. If one wants beautifying options we should design a system to pass them down. Besides, I do not like the Raleway font as it renders poorly on screens (but that, of course, it is a matter of taste!).

**Comment by mpastell** [comment]
I do like the idea of having a default theme that is not totally vanilla, but having options and maybe passing a custom template would be useful. Do you have a suggestion for better default font?
