### ISSUE TITLE
Export/import to/from Jupyter notebook

### ISSUE THREAD

**Issue by dpsanders** [mpastell/Weave.jl#48]
It would be great to be able to export to and from a Jupyter notebook format.
Would this be at all possible (or is it already)?

**Comment by mpastell** [comment]
This is currently not possible, but it would not be too hard to implement in a way that you'd just convert the text and code cells/chunks to/from notebook format. Adding support for jupyter magics etc. I guess would require running the weave code using IJulia.

**Comment by mpastell** [comment]
You can now Weave notebooks simply using 

``` julia
weave("somenotebook.ipynb")
```

I will look into converting between formats to get output as well.

**Comment by mpastell** [comment]
I added converting between different Weave formats and notebooks. Examples:

```julia
 convert_doc("examples/FIR_design.jl", "FIR_design.ipynb")
 convert_doc("FIR_design.ipynb", "FIR_design.jmd")
```

**Comment by dpsanders** [comment]
Looks nice, thanks!

**Comment by mpastell** [comment]
Glad if you find it useful. @dpsanders what's your main use case for this?

**Comment by dpsanders** [comment]
Thinking about reproducible workflows and how to extract information from notebooks. I haven't had a chance to think about it more in detail.

**Comment by mpastell** [comment]
Ok, feel free to open more issues if you come up with good ideas. I think I may use this myself to share analysis written using markdown/script format as notebooks. I prefer to work with Atom/Emacs instead of notebooks.
