### ISSUE TITLE
Citations and bibliography

### ISSUE THREAD

**Issue by bramtayl** [mpastell/Weave.jl#50]
rmarkdown has support for citations and bibliographies. This would be a cool feature to add if it doesn't exist, and I could pitch in porting the code if you want?

http://rmarkdown.rstudio.com/authoring_bibliographies_and_citations.html

**Comment by mpastell** [comment]
Weave.jl also used Pandoc so citations just work the same if you output to markdown. 

You may need change the templates and Pandoc call for html and pdf outputs, I actually haven't tried it.

**Comment by sylvaticus** [comment]
Hello @mpastell , thanks for this great package.
Could you elaborate a bit more on how to handle citations in Weave ?
I couldn't find it in the package documentation and this question seems the only source of info ;-)

I did follow the page linked by @bramtayl, inserted `bibliography: biblio.bib` (biblio.bib is where I keep all my references) into the preamble of the testRef.jmd file and tried to put some citations within the file, but these are not compiled when I run either
`weave("testRef.jmd", out_path = :pwd,  doctype = "md2pdf")` 
or
`weave("testRef.jmd", out_path = :pwd,  doctype = "pandoc")` 

testRef.jmd:

```
---
title : Test with citations
date : 14th March 2017
bibliography: biblio.bib
---

Test [see @Allen:2010, pp. 33-35; also @Archer:2009, ch. 1].

@Arfini [p. 33] says blah.

The above references should have been compiled 
```

**Comment by mpastell** [comment]
@sylvaticus I changed the pandoc templates to process citations and "pandoc" format to leave the header in the file. So with the current master this should work

```julia
weave("testRef.jmd", out_path = :pwd, doctype = "pandoc2pdf")
weave("testRef.jmd", out_path = :pwd, doctype = "pandoc2html")
``` 

If you want to use pandoc directly (with different options, template etc.) first run

````julia
weave("testRef.jmd", out_path = :pwd, doctype = "pandoc")
```

And call pandoc

```shell
pandoc testRef.md --filter pandoc-citeproc -o testRef.pdf
```

**Comment by sylvaticus** [comment]
Works great, thank you.
On Ubuntu 16.04 you need the packages `pandoc-citeproc` and  `texlive-xetex` installed.
