### ISSUE TITLE
ERROR: syntax: { } vector syntax is discontinued

### ISSUE THREAD

**Issue by sje30** [mpastell/Weave.jl#54]
Running weave on one of the examples generates the following errors:

```
julia> weave("julia_sample.mdw")
INFO: Recompiling stale cache file /Users/stephen/.julia/lib/v0.5/Gadfly.ji for module Gadfly.
INFO: Weaving chunk 1 from line 18
ERROR: syntax: { } vector syntax is discontinued
 in capture_output(::Expr, ::Module, ::Bool, ::String) at /Users/stephen/.julia/v0.5/Weave/src/run.jl:142
 in run_code(::Weave.CodeChunk, ::Weave.Report, ::Module) at /Users/stephen/.julia/v0.5/Weave/src/run.jl:121
 in eval_chunk(::Weave.CodeChunk, ::Weave.Report, ::Module) at /Users/stephen/.julia/v0.5/Weave/src/run.jl:189
 in run_chunk(::Weave.CodeChunk, ::Weave.Report, ::Module) at /Users/stephen/.julia/v0.5/Weave/src/run.jl:100
 in #run#7(::Symbol, ::String, ::Symbol, ::String, ::Void, ::String, ::Symbol, ::Function, ::Weave.WeaveDoc) at /Users/stephen/.julia/v0.5/Weave/src/run.jl:67
 in (::Base.#kw##run)(::Array{Any,1}, ::Base.#run, ::Weave.WeaveDoc) at ./<missing>:0
 in #weave#4(::Symbol, ::String, ::Symbol, ::Symbol, ::String, ::Void, ::String, ::Symbol, ::Weave.#weave, ::String) at /Users/stephen/.julia/v0.5/Weave/src/Weave.jl:104
 in weave(::String) at /Users/stephen/.julia/v0.5/Weave/src/Weave.jl:103
```

This is with julia 0.5 on mac with latest release of Weave

**Comment by sje30** [comment]
Fixing the  syntax error was easier than I realised. e.g. julia_sample.mdw change line 20 to
```
d = Dict("Weave" => "testing")
```

The doc then compiles, but I see no figures in the html doc (graphs appear on the screen during Weaving.)

**Comment by mpastell** [comment]
Thanks for reporting. I haven't fixed Weave to work with 0.5 yet, but I will try to find time to do it.

**Comment by mpastell** [comment]
I could not reproduce the error, the document compiles without problems (with fixed Dict syntax) and the graphs are included. I'm using Julia 0.5 with Ubuntu 16.04, I don't have access to Mac Os X.

You could try using current master to see if it works.

**Comment by sje30** [comment]
Thanks.  I've made some progress.  If I run with version 1 below, the plots are included; with version 2 or 3, they are not made.

```
weave("julia_sample.mdw", plotlib="PyPlot") # 1, works
weave("julia_sample.mdw", plotlib="Gadfly") #2, no plots
weave("julia_sample.mdw") #3, no plots
```

**Comment by mpastell** [comment]
Hi,
That is how it is supposed to work with v0.1.2. With the just tagged 0.2 also #1 will work.

**Comment by sje30** [comment]
Okay, thanks!
