### ISSUE TITLE
Creating tables with thead and tbody tags

### ISSUE THREAD

**Issue by phillc73** [mpastell/Weave.jl#59]
I'd like to create some HTML tables using Weave.jl. However, the HTML output is not strictly speaking correct. The `thead` and `tbody` tags are missing. I would like to include these tags, as they are required to support some further UI changes I'd like to make. Unfortunately, I can't see an option to force this.

I've had a look at [getskeleton.com](http://getskeleton.com/#tables) as well, and they also specify that these two tags *should* be included.

Here's some example code I am Weaving to create an HTML page with table output:

```
```{julia;echo=false}

using DataFrames
using RDatasets

mtcars = dataset("datasets","mtcars")

mtcars

 ```

I'm using the following to Weave:

```
weave("datframetest.jmd", out_path = :pwd, doctype = "md2html")
```

The HTML page is created fine and the table also displays reasonably well, just that those two tags are not present in the table code.

As a related question, and happy to open a separate issue if required, is there a way to set the table `id`?

**Comment by mpastell** [comment]
The html output is produced by DataFrames.jl so it is better to open the issue of missing tags there. 

I think this is the relevant file if you want to make a pull request:
https://github.com/JuliaStats/DataFrames.jl/blob/203b50ff197ae418e4f1371cc82e5581a7caf5f1/src/abstractdataframe/io.jl

There is currently no way to set the table id, please open it as another issue.
