### ISSUE TITLE
Extra space in first line of an output chunk?

### ISSUE THREAD

**Issue by sje30** [mpastell/Weave.jl#61]
Hi,

I've noticed that the first part of an output chunk has an extra space before the text.  You can see it on your example image:

https://camo.githubusercontent.com/7fa0f44fea8c9ee7a4927c6909cef3dc52074e36/687474703a2f2f6d70617374656c6c2e636f6d2f696d616765732f77656176655f64656d6f2e706e67

note how the line `Using Gadfly` appears in the left window (without space before it) and with one space (in the output window) on the right.

**Comment by sje30** [comment]
you can also see it at the bottom right of the image, where `julia> x=1:10` is written.

**Comment by mpastell** [comment]
Thanks for report, I'll look into it.

**Comment by mpastell** [comment]
This has been fixed in the new template using Julia markdown `md2html`. It replaces the old pandoc based  output as the default. The pandoc version is now called `pandoc2html` and still has this bug.
