### ISSUE TITLE
Have option to surpress generation of figure files

### ISSUE THREAD

**Issue by davidanthoff** [mpastell/Weave.jl#69]
When I'm generating an html output file right now by essentially specifying only the input file, I get one html file plus a bunch of png files in the folder png. But those png files seem unnecessary, given that the graphics are already embedded in the html file.  Would be nice if there was an option so that the only file generated is the html file (or maybe even make that the default?).

**Comment by mpastell** [comment]
I will fix this, the figures are just an artifact left from running the code and I think they should always be removed.

**Comment by davidanthoff** [comment]
Great! And the folder as well? Maybe just use [this](http://docs.julialang.org/en/latest/stdlib/file.html#Base.Filesystem.mktempdir-Tuple{Function,Any}) to create the folder?

**Comment by davidanthoff** [comment]
And I just realized that when I weave a jmd file, it generates an html and a md file in the directory. Is there some way to suppress the generation of the md file as well?

**Comment by mpastell** [comment]
Not currently, but I will fix it as well.

**Comment by davidanthoff** [comment]
Same with pdf files, and I assume some other formats as well. It would just generally be nice if the only file generated is the one requested, and nothing else.

**Comment by mpastell** [comment]
It only happens for html and pdf (as other formats need to call pandoc, latex etc. and need the figures) I'm already working on a fix that will work pdf's as well.

**Comment by mpastell** [comment]
Note that figures can't be removed when caching is used (well they could be for md2html but that needs more changes that I don't have time to do right now, but not for other formats).

**Comment by mpastell** [comment]
Ok, so adding the temporary directory breaks figure pdf generation windows...

**Comment by mpastell** [comment]
And fixed with  458ef30. I also implemented caching of embedded figures for html anyway so no extra files are left in the directory after a succesful call to weave.

**Comment by davidanthoff** [comment]
Excellent!
