### ISSUE TITLE
Handling of Windows line endings seems buggy

### ISSUE THREAD

**Issue by davidanthoff** [mpastell/Weave.jl#72]
In general, the code does not seem to deal with Windows style line-endings well.

In its most basic form, the tests don't pass on Windows if the repository is cloned with the git config ``autocrlf=true`` (the recommended setting on Windows). What happens is that all the reference output files  are stored on disc with ``\r\n`` line endings, but then the files that are written by Weave use ``\n`` as the line ending, and all the comparisons fail. So the problem here is that Weave writes files that use Unix line ending on Windows machine, whereas it should probably use ``\r\n`` when it writes files on Windows.

I think this also affects things on the input side. The parsing error I originally described in #70 seems to go away when I clone the repo with ``autocrlf=false``, which suggests to me that the code right now doesn't handle input files properly that use ``\r\n`` for line endings.

**Comment by mpastell** [comment]
David, many thanks for testing Weave on windows. I do not use it a lot on windows myself and the testing clearly has been incomplete.

I would be tempted to:

1. Always convert `\r\n` to when reading documents `\n` 
2. Always write files using `\n`

Do you think that would be OK?

**Comment by davidanthoff** [comment]
I think that would work. You would also have to add a ``.gitattributes`` file that makes sure all your reference files get checked out using ``\n``, but at that point I think things should work.

**Comment by mpastell** [comment]
It should be fixed now, but I haven't tested doing a git clone yet so I'll leave the issue open.

**Comment by davidanthoff** [comment]
Just tested it, all the tests pass now!

**Comment by mpastell** [comment]
Great, thanks for testing!
