### ISSUE TITLE
Install pandoc automatically

### ISSUE THREAD

**Issue by davidanthoff** [mpastell/Weave.jl#73]
Not sure this is actually a good idea, so more a discussion item.

There could be a build.jl script that downloads the [binary distribution](https://github.com/craigcitro/r-travis/issues/136#issuecomment-63169431) of pandoc that is used by RStudio, extracts it and then the package could use that and would no longer require a system installed version of pandoc.

This might make no sense on Linux and Mac (do they have pandoc installed by default?), but on Windows it would make life quite a bit easier for users because things would "just work".

If you are in general ok with this plan, I could prep a PR.

**Comment by mpastell** [comment]
As of 0.3 (not merged yet) Weave converts markdown to html and latex without pandoc. There is still the option the to use pandoc as well.

So I think currently it's maybe better not to download pandoc with Weave.

It could be nice to have something like Pandoc.jl as its own package that would download Pandoc on different platforms.

**Comment by mpastell** [comment]
Pandoc is not installed on Ubuntu by default, it is in the repositories but then the version can be quite old.

**Comment by davidanthoff** [comment]
Ah, yes, that makes total sense.
