### ISSUE TITLE
Roadmap 2017

### ISSUE THREAD

**Issue by mpastell** [mpastell/Weave.jl#79]
This a general roadmap issue for Weave to discuss further plans.

I see at least 2 important missing features:

- [x] Inline code #77, #80  
- [x] Pass variables to documents #78 
- [ ] Improved examples. Go trough examples and leave only sensible ones. Add a script to run all examples, maybe example gallery similar to Pweave. http://mpastell.com/pweave/examples/index.html

There is no timetable as development takes place in my limited spare time, but I hope to get these implemented around the time of Julia 1.0. 

Contributions and new ideas are very welcome!

**Comment by ValdarT** [comment]
Functionality akin to R’s [flexdashboard](http://rmarkdown.rstudio.com/flexdashboard/) would be nice. 

It should probably be a separate package but I wanted to throw the idea out there and this seemed like an appropriate place.
