### ISSUE TITLE
Don't halt on errors

### ISSUE THREAD

**Issue by mpastell** [mpastell/Weave.jl#81]
It would probably be better to to include the error messages in output document instead of halting on errors.

**Comment by kescobo** [comment]
Was going to come and ask for this :-). Even if the default behavior stays the same and there's an optional flag like `echo = false` for some code block. I think under most circumstances I wouldn't want errors to go through silently, but there are definitely times when I'd explicitly like to show the error.

Keep up the great work! Only been using this for a few days, but loving it!

**Comment by mykelk** [comment]
This would be great. I think it would help with [this issue](https://github.com/gpoore/pythontex/issues/98) in pythontex.

**Comment by mpastell** [comment]
This is on my todo list, I will try to find time to support it,

**Comment by gpoore** [comment]
For the `term=true` case, if there are ever any errors that can't be included in the output *document* like normal terminal errors, then it would be nice to have the option of the `weave()` output *in julia* including a line with the word `ERROR` and the source name and line number, or something similar. PythonTeX scans the stderr of all code it executes for (customizable) messages of that form, and can use the line number in the source that was executed to determine where that code originated in a `.tex` document.

**Comment by mpastell** [comment]
It took me quite long to find the time to implement this, but it should work well now. @gpoore I don't think there should be any errors that can't be included in the output so I didn't implement the line number display. I can try to look into it if it turns out it's needed.
