### ISSUE TITLE
Extra and blank lines in `term=true` output

### ISSUE THREAD

**Issue by dpsanders** [mpastell/Weave.jl#82]
There is an extra blank line in the Gadfly example with terminal (REPL) output after `1:10`, but no blank line before the next `julia` prompt. 

I tried to look at the source code to change this myself, but couldn't work out where to change.

**Comment by dpsanders** [comment]
(By the way, there seems to be inconsistent indentation in `format.jl`.)

**Comment by mpastell** [comment]
Thanks for reporting the issue. It should be fixed now.  (good point about inconsistent indentation, its not fixed yet)
