### ISSUE TITLE
actual and src path for figures

### ISSUE THREAD

**Issue by tpapp** [mpastell/Weave.jl#84]
Would it be possible to have two paths instead of `fig_path`, 

1. one where the actual images end up (eg `../../static/figures/`)
2. one which is then encoded as the path in the generated file (eg `/figures/`)?

This would allow a nicer generation workflow with Hugo.

**Comment by tpapp** [comment]
Thinking about this, it would be even nicer if the user could specify a function (or a general callable object) for inserting image markup in the code. Eg 
```julia
function image_markup(fig_path, fig_filename, backend)
    if backend == :markdown
        "![](" * joinpath(fig_path, fig_filename) * ")"
    elseif
        ...
    end
end
```
would be used for the current behavior, but could be customized to insert [shortcodes](https://gohugo.io/extras/shortcodes/#figure), etc.

**Comment by mpastell** [comment]
Thanks for the suggestion. I will need to think about it and I don't have time to work on it right now. 

One solution here would be to add a formatter for Hugo. You can see how output formats are implemented in : https://github.com/mpastell/Weave.jl/blob/master/src/formatters.jl . Adding a separate output format would allow to use the shortcode for syntax highlighting as well.

**Comment by tpapp** [comment]
Added PR #86 following your suggestion (it was easier than expected). The fix is Hugo-specific, and does not address the general issue above, however, it works for what I want to do.
