### ISSUE TITLE
Unicode symbols in pdflatex output

### ISSUE THREAD

**Issue by c42f** [mpastell/Weave.jl#90]
Thanks for Weave, the general approach is exactly what I've been wanting for scientific reports containing code.

One problem I'm struggling with is that julia code is very unicode friendly, but this doesn't render properly via the pdflatex backend.  So far I've been extending the tex template to hack around this problem with something like

```tex
\lstset{
       literate={ζ}{\ensuremath{\zeta}}1 {α}{\ensuremath{\alpha}}1
}
```

as well as adding a bunch of `\newunicodechar` commands, though I'm not sure that's the right approach.

Do you have any thoughts about the correct way to handle this?

A very basic example which I'm trying to process

```
Some symbols: α β γ δ ζ

Some symbols in math mode: $α β γ δ ζ$

Some symbols in code:
```julia
ζ = 1
@show ζ
``
```

**Comment by mpastell** [comment]
First of all I think this should just work and I will look into it.

For now you can add the following to the template:

```
\usepackage{fontspec}
\setmainfont{TeX Gyre Pagella}
\setmonofont{CMU Typewriter Text}
```
And can call Weave using:

```julia
weave("mydoc.jmd", doctype="md2pdf", latex_cmd="lualatex")
```

**Comment by mpastell** [comment]
There are of course other options than `Tex Gyre Pagella`  e.g.   `\setmainfont{CMU Serif}`

**Comment by c42f** [comment]
Great, thanks!  This morning I already tried running xelatex against it, but when that didn't work immediately I went back to messing with pdflatex.  Then I ran out of time!

I tried luatex and I still had font issues - all symbols were missing, despite adding the snippet above to the preamble. Eventually I've tracked this down to the chunk added by `Highlights.jl`, which adds a problematic `\usepackage[T1]{fontenc}`.  It seems this interacts badly with `fontspec`, but can be worked around by adding your snippet *after* the chunk `{{{ :highlight }}}` in the template.

Also, it looks like we'll need something like

```latex
\usepackage{unicode-math}
\setmathfont{TeX Gyre Pagella Math}
```

to make unicode work in math mode.  I'm afraid the Gyre Pagella Math fonts aren't that pleasing to my eye, but at this stage I'm happy just to have something mostly working!

**Comment by c42f** [comment]
Aha, `\setmathfont{Latin Modern Math}` gives the classic TeX math fonts which seem to work fine for this purpose.  Unfortunately, I don't seem to be able to get `\setmonofont{Latin Modern Typewriter}` to work at all (all I get is a font not found error). Perhaps it just doesn't exist in the texlive distribution for ubuntu 16.04.

**Comment by baggepinnen** [comment]
I'm still having issues with some symbols, in particular ∈, ∉
which are commonly used but not rendered. My tests are with lualatex.

**Comment by mpastell** [comment]
Do you have any suggestions for a fix? Is there a font that would fix it? I use Luatex only very occasionally, but I will investigate at some point

**Comment by baggepinnen** [comment]
`\setmonofont{DejaVu Sans Mono}` works well for me
