### ISSUE TITLE
Support of Python Markdown

### ISSUE THREAD

**Issue by heliosdrm** [mpastell/Weave.jl#95]
Perhaps a silly question, but...

The combination of Weave.jl and MkDocs is a nice way to publish documentation that includes Julia code (Weave's documentation itself is built that way). But MkDocs reports using "Python Markdown" to create HTML files, whereas Weave.jl's supported markdown formats for output are:

github: Github markdown
pandoc: Pandoc markdown
multimarkdown: MultiMarkdown

Is any of those outputs better suited than the others for Python Markdown? Would it be necessary to include yet another format to match that specific flavor?

**Comment by mpastell** [comment]
I use github markdown with mkdocs and I don't think there are any differences. I will add new formats if needed.

**Comment by heliosdrm** [comment]
Thanks! If Python Markdown works fine with github-flavored md files, I don't think there is need to add yet another format for this purpose. Perhaps it's rather an issue of documentation, but not especially of Weave.jl. It's just that the variety of markdown flavors is a bit of a mess.
